### ISSUE TITLE
Establish event location

### ISSUE THREAD

**Issue by han-so1omon** [ingenierias-lentas/community#1]
### What needs to be done

Find location to host events. Need price, hours, accessibility

### Why it needs to be done

Location is required in order to run events effectively

### Stories

As an organizer, I want to know where the event takes place so that I can prepare appropriately

As a community member, I want to know where the event takes place so that I can plan accordingly to show up and participate

**Comment by danolar** [comment]
The site selected for the first event is a meeting room provided by **Centro de alta tecnología (CAT)** located at: [Cl. 77 #15-58, Bogotá.](https://goo.gl/maps/b3CRkSAdzzsvrs6RA)

The site has the following benefits:

- Up to 70 people
- video projectors
- dedicated 50mb wifi
- electric curtains
- stereo sound
- Lectern
- air conditioning
- Chairs and tables upon request
