### ISSUE TITLE
Draft website content

### ISSUE THREAD

**Issue by han-so1omon** [ingenierias-lentas/community#6]
### What needs to be done

Draft content for website

### Why it needs to be done

Website needs to have basic information

**Comment by danolar** [comment]
Pages configured and finished following the draft guide created in figma.

Pending revision of details

https://web3partners.community/

![screencapture-web3partnersmunity.png](https://images.zenhubusercontent.com/63c9bc8f95e3a5cb295f4867/de30f6d0-1946-4dd0-b4ff-8d8b34086591)

https://bogota.web3partners.community/

![screencapture-bogota-web3partnersmunity.png](https://images.zenhubusercontent.com/63c9bc8f95e3a5cb295f4867/8d3cbd40-834f-46df-ae37-99457b161eea)
